# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "ntfs" "btrfs" ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6fc64aeb-0510-49ce-bc24-f113403c5a40";
      fsType = "btrfs";
      options = [ "subvol=nixos-root" "compress=zstd" "noatime" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/6fc64aeb-0510-49ce-bc24-f113403c5a40";
      fsType = "btrfs";
      options = [ "subvol=nixos-nix" "compress=zstd" "noatime" ];
    };

    "/home/gavin" = {
      device = "/dev/disk/by-uuid/6fc64aeb-0510-49ce-bc24-f113403c5a40";
      fsType = "btrfs";
      options = [ "subvol=nixos-home" "compress=zstd" "noatime" ];
    };

    "/home/gavin/my" = {
      device = "/dev/disk/by-uuid/9db75b93-b1f5-4f8b-a686-aa1833b4bede";
      fsType = "btrfs";
      options = [ "subvol=personal" "compress=zstd" "noatime" ];
    };

    "/home/gavin/games" = {
      device = "/dev/disk/by-uuid/9db75b93-b1f5-4f8b-a686-aa1833b4bede";
      fsType = "btrfs";
      options = [ "subvol=games" "compress=zstd" "noatime" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/7E63-C84E";
      fsType = "vfat";
    };
  };

  swapDevices = [ ];

}
